// <auto-generated />
using System;
using Bibliotek_Labb1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bibliotek_Labb1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220919140543_AddedSeedDataForImageAndDescriptionProperties")]
    partial class AddedSeedDataForImageAndDescriptionProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bibliotek_Labb1.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsOnLoan")
                        .HasColumnType("bit");

                    b.HasKey("BookID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            Author = "J.R.R. Tolkien",
                            BookName = "The Hobbit",
                            Description = "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
                            ImageThumbnailUrl = "\\Images\\TheHobbit1.jpg",
                            IsOnLoan = true
                        },
                        new
                        {
                            BookID = 2,
                            Author = "J.R.R. Tolkien",
                            BookName = "The Fellowship of the Ring",
                            Description = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkeness bind them.In ancient times the Rings of Power were crafted by the Elven - smiths, and Sauron, The Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others.But the One Ring was taken from him, and though he sought it throughout Middle - earth, it remained lost to him.After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit.In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care.Frodo must leave his home and make a perilous journey across Middle - earth to the Cracks of Doom,there to destroy the Ring and foil the Dark Lord in his evil purpose.",
                            ImageThumbnailUrl = "\\Images\\TheFellowshipOfTheRing1.gif",
                            IsOnLoan = true
                        },
                        new
                        {
                            BookID = 3,
                            Author = "J.R.R. Tolkien",
                            BookName = "The Two Towers",
                            Description = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.",
                            ImageThumbnailUrl = "\\Images\\TheTwoTowers1.jpg",
                            IsOnLoan = false
                        },
                        new
                        {
                            BookID = 4,
                            Author = "J.R.R. Tolkien",
                            BookName = "The Return of the King",
                            Description = "One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.The Dark Lord has risen, and as he unleashes hordes of Orcs to conquer all Middle-earth, Frodo and Sam struggle deep into his realm in Mordor. To defeat Sauron, the One Ring must be destroyed in the fires of Mount Doom. But the way is impossibly hard, and Frodo is weakening. The Ring corrupts all who bear it and Frodo’s time is running out. Will Sam and Frodo succeed, or will the Dark Lord rule Middle-earth once more? ",
                            ImageThumbnailUrl = "\\Images\\TheReturnOfTheKing.jpg",
                            IsOnLoan = true
                        },
                        new
                        {
                            BookID = 5,
                            Author = "Harper Lee",
                            BookName = "To Kill A Mockingbird",
                            Description = "Scout, the keen-eyed narrator, and her brother Jem interrupt their games to champion their lawyer father when, in a hostile, racist town in the American South, he battles to defend Tom, who is black and accused of murder.",
                            ImageThumbnailUrl = "\\Images\\ToKillAMockingBird1.jpg",
                            IsOnLoan = false
                        },
                        new
                        {
                            BookID = 6,
                            Author = "F.Scott Fitzgerald",
                            BookName = "The Great Gatsby",
                            Description = "'It was one of those rare smiles with a quality of eternal reassurance in it, that you may come across four or five times in life'Jay Gatsby is the man who has everything. But one thing will always be out of his reach ... Everybody who is anybody is seen at his glittering parties. Day and night his Long Island mansion buzzes with bright young things drinking, dancing and debating his mysterious character. For Gatsby - young, handsome, fabulously rich - always seems alone in the crowd, watching and waiting, though no one knows what for. Beneath the shimmering surface of his life he is hiding a secret: a silent longing that can never be fulfilled. And soon this destructive obsession will force his world to unravel.",
                            ImageThumbnailUrl = "\\Images\\TheGreatGatsby1.jpg",
                            IsOnLoan = false
                        },
                        new
                        {
                            BookID = 7,
                            Author = "Charles Dickens",
                            BookName = "Oliver Twist",
                            Description = "The story of the orphan Oliver, who runs away from the workhouse only to be taken in by a den of thieves, shocked readers when it was first published. Dickens's tale of childhood innocence beset by evil depicts the dark criminal underworld of a London peopled by vivid and memorable characters - the arch-villain Fagin, the artful Dodger, the menacing Bill Sikes and the prostitute Nancy. Combining elements of Gothic Romance, the Newgate Novel and popular melodrama, Dickens created an entirely new kind of fiction, scathing in its indictment of a cruel society, and pervaded by an unforgettable sense of threat and mystery.",
                            ImageThumbnailUrl = "\\Images\\OliverTwist1.jpg",
                            IsOnLoan = true
                        },
                        new
                        {
                            BookID = 8,
                            Author = "Mary Shelley",
                            BookName = "Frankenstein",
                            Description = "Obsessed by creating life itself, Victor Frankenstein plunders graveyards for the material to fashion a new being, which he shocks into life by electricity. But his botched creature, rejected by Frankenstein and denied human companionship, sets out to destroy his maker and all that he holds dear. ",
                            ImageThumbnailUrl = "\\Images\\Frankenstein1.jpg",
                            IsOnLoan = false
                        },
                        new
                        {
                            BookID = 9,
                            Author = "Emily Brönte",
                            BookName = "Wuthering Heights",
                            Description = "In a house haunted by memories, the past is everywhere … As darkness falls, a man caught in a snowstorm is forced to shelter at the strange, grim house Wuthering Heights. It is a place he will never forget. There he will come to learn the story of Cathy: how she was forced to choose between her well-meaning husband and the dangerous man she had loved since she was young. How her choice led to betrayal and terrible revenge - and continues to torment those in the present. How love can transgress authority, convention, even death. And how desire can kill.",
                            ImageThumbnailUrl = "\\Images\\WutheringHeights1.jpg",
                            IsOnLoan = false
                        },
                        new
                        {
                            BookID = 10,
                            Author = "Heman Melville",
                            BookName = "Moby Dick",
                            Description = "In Herman Melville's Moby-Dick, Captain Ahab is an eerily compelling madman who focuses his distilled hatred and suffering (and that of generations before him) into the pursuit of a creature as vast, dangerous and unknowable as the sea itself. More than just a novel of adventure, this is a haunting social commentary populated with some of the most enduring characters in literature. Written with wonderfully redemptive humour, Moby Dick is a profound and timeless inquiry into character, faith and the nature of perception.",
                            ImageThumbnailUrl = "\\Images\\MobyDick1.jpg",
                            IsOnLoan = true
                        },
                        new
                        {
                            BookID = 11,
                            Author = "Toni Morrison",
                            BookName = "Song of Solomon",
                            Description = "Macon Dead, Jr., called 'Milkman,'the son of the wealthiest African American in town, moves from childhood into early manhood, searching, among the disparate, mysterious members of his family, for his life and reality. ",
                            ImageThumbnailUrl = "\\Images\\SongOfSolomon.jpeg",
                            IsOnLoan = false
                        });
                });

            modelBuilder.Entity("Bibliotek_Labb1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerID = 1,
                            Adress = "Skamman 13",
                            City = "Varberg",
                            Email = "HannaH@gmail.com",
                            FullName = "Hanna Lahtinen",
                            ZipCode = "43246"
                        },
                        new
                        {
                            CustomerID = 2,
                            Adress = "Storgatan 6",
                            City = "Varberg",
                            Email = "J.Gergi@gmail.com",
                            FullName = "Jennifer Gergi",
                            ZipCode = "43246"
                        },
                        new
                        {
                            CustomerID = 3,
                            Adress = "Varberg",
                            City = "Storgatan 2",
                            Email = "Winborg.98@hotmail.com",
                            FullName = "Markus Winborg",
                            ZipCode = "43246"
                        },
                        new
                        {
                            CustomerID = 4,
                            Adress = "Skammerhult 16",
                            City = "Nösslinge",
                            Email = "SofiaKarlsson98@gmail.com",
                            FullName = "Sofia Karlsson",
                            PhoneNumber = "0738428987",
                            ZipCode = "43299"
                        });
                });

            modelBuilder.Entity("Bibliotek_Labb1.Models.CustomerBook", b =>
                {
                    b.Property<int>("CustomerBookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BookBorrowed")
                        .HasColumnType("datetime2");

                    b.Property<int>("BookID")
                        .HasColumnType("int");

                    b.Property<DateTime>("BookReturned")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.HasKey("CustomerBookID");

                    b.HasIndex("BookID");

                    b.HasIndex("CustomerID");

                    b.ToTable("CustomerBooks");

                    b.HasData(
                        new
                        {
                            CustomerBookID = 1,
                            BookBorrowed = new DateTime(2022, 7, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookID = 1,
                            BookReturned = new DateTime(2022, 8, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1
                        },
                        new
                        {
                            CustomerBookID = 2,
                            BookBorrowed = new DateTime(2022, 8, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BookID = 2,
                            BookReturned = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerID = 1
                        });
                });

            modelBuilder.Entity("Bibliotek_Labb1.Models.CustomerBook", b =>
                {
                    b.HasOne("Bibliotek_Labb1.Models.Book", "Book")
                        .WithMany("CustomerBook")
                        .HasForeignKey("BookID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bibliotek_Labb1.Models.Customer", "Customer")
                        .WithMany("CustomerBook")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
